all: print_module documentation_module

print_module:
	gcc -Wextra -Werror -Wall main_module_entry_point.c print_module.c documentation_module.c -o ../build/Quest_1

documentation_module: 
	gcc -Wextra -Werror -Wall main_module_entry_point.c print_module.c documentation_module.c -o ../build/Quest_2